# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'Default'  # Specify your agent pool here, assuming 'Default' is correct
  demands:
    - agent.name -equals ECK  # Ensures the pipeline uses your self-hosted agent named 'ECK'


steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'